const ADD_BASKET = 'ADD_BASKET';
const REMOVE_BASKET = 'REMOVE_BASKET';
const ADD_ROOM = 'ADD_ROOM';
const REMOVE_ROOM = 'REMOVE_ROOM';
const ADD_DATA = 'ADD_DATA';
const REMOVE_DATA = 'REMOVE_DATA';
const ADD_FILM = 'ADD_FILM';
const  UPDATE_BANNER = ' UPDATE_BANNER';

export { UPDATE_BANNER, ADD_BASKET, REMOVE_BASKET, ADD_ROOM, REMOVE_ROOM, ADD_DATA, REMOVE_DATA, ADD_FILM};
